name: ponto-crz
base: core24
icon: snap/gui/icon.png
title: PontoCrz
version: '1.0.1'
license: MIT
contact: https://github.com/erascardsilva/pontoCrz/issues
website: https://github.com/erascardsilva/pontoCrz
summary: Transforme fotos em gráficos de ponto cruz
description: |
  PontoCrz é uma ferramenta para transformar suas fotos favoritas em 
  gráficos técnicos de ponto cruz (cross stitch).
  Escolha a largura em pontos, a quantidade de cores DMC e salve em JPG
  pronto para imprimir e bordar à mão.

grade: stable
confinement: strict

apps:
  ponto-crz:
    command: bin/pontoCrz
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - x11
      - wayland

parts:
  app:
    plugin: dump
    source: build/bin/
    organize:
      pontoCrz: bin/pontoCrz
