// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function PickFile():Promise<string>;

export function ProcessImage(arg1:string,arg2:number,arg3:number):Promise<backend.ProcessedImage>;

export function SaveImage(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;
